language: r
sudo: false
cache: packages
r:
  - devel
#  - oldrel
#  - release

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
