language: r
sudo: false
cache: packages
env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

r:
  - devel
  - release
  - oldrel

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
