language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
