language: r
sudo: required

warnings_are_errors: true

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'library(irlba); covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
